# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mmitkovi <mmitkovi@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/11/06 13:28:40 by mmitkovi          #+#    #+#              #
#    Updated: 2025/11/06 13:31:41 by mmitkovi         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	:= megaphone
CXX		:= c++
CXXFLAGS:= -Wall -Wextra -Werror -std=c++98

SRCS	:= megaphone.cpp
OBJS	:=